name: quality-check

on:
  push:
   branches:
   - main
  pull_request:
    branches:
    - main

jobs:
  quality_check:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: docker-compose up --build unit-test
      - name: Upload coverage to Codecov
        if: success() && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v1
        with:
          directory: ./test-reports/
          flags: unit-tests
          fail_ci_if_error: true
      - name: Run e2e tests
        run: docker-compose up --build e2e-test
      - name: Upload coverage to Codecov
        if: success() && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v1
        with:
          directory: ./e2e-reports/
          flags: e2e-tests
          fail_ci_if_error: true
      - name: Lint Python code
        run: docker-compose up --build lint
